# Generated by Django 5.0 on 2023-12-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered',
            field=models.DateTimeField(null=True, verbose_name='Заказано'),
        ),
    ]
