# Generated by Django 5.0 on 2023-12-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, choices=[('---', '---'), ('NEW', 'Новый'), ('CONFIRMED', 'Подтвержден'), ('CANCELLED', 'Отменен')], default='---', max_length=9, verbose_name='Статус'),
        ),
    ]
