# Generated by Django 5.0 on 2023-12-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cart_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='cart_user_ordered',
        ),
    ]
