# Generated by Django 5.0 on 2023-12-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_remove_cart_cart_user_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_uuid',
            field=models.UUIDField(default=1, unique=True, verbose_name='ID заказа'),
            preserve_default=False,
        ),
    ]
