# Generated by Django 5.0 on 2023-12-27 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cart_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID заказа'),
        ),
    ]
