# Generated by Django 5.0 on 2023-12-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_alter_cart_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_uuid',
            field=models.UUIDField(null=True, verbose_name='ID заказа'),
        ),
    ]
