# Generated by Django 5.0 on 2023-12-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rules',
            field=models.BooleanField(verbose_name='Согласен с правилами регистрации'),
        ),
    ]
