# Generated by Django 5.0 on 2023-12-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток товара'),
        ),
    ]
