# Generated by Django 5.0 on 2023-12-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Тип упаковки', 'verbose_name_plural': 'Типы упаковки'},
        ),
    ]
