# Generated by Django 5.0 on 2023-12-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_goods_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='Фото',
            new_name='photo',
        ),
    ]
