# Generated by Django 5.0 on 2023-12-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_rename_фото_goods_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='manufactured',
            new_name='origin',
        ),
    ]
