# Generated by Django 5.0 on 2023-12-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_rename_manufactured_goods_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='package',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='type',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория/Вид товара', 'verbose_name_plural': 'Категории/Виды товаров'},
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
