# Generated by Django 5.0 on 2024-01-02 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c4ec087-e393-4849-b796-51e44e2079f6'), primary_key=True, serialize=False),
        ),
    ]
