# Generated by Django 5.0 on 2023-12-28 07:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_cause',
            field=models.TextField(blank=True, default='', verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8fc0d404-cbd4-4ea5-8a2f-6f0485d521ae'), primary_key=True, serialize=False),
        ),
    ]
