# Generated by Django 5.0 on 2023-12-29 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a6f07a56-bd47-4844-813d-697faf6f5f58'), primary_key=True, serialize=False),
        ),
    ]
