# Generated by Django 5.0 on 2023-12-29 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64e63e00-9630-4165-80d8-d012b5425b39'), primary_key=True, serialize=False),
        ),
    ]
